#!/bin/bash

# Default values
WORKLOAD="llama.cpp"
BASE="ubuntu"
PAUSE=10
OPTIONS=()
COMMAND=()
INFERENCE="Building a website can be done in 10 simple steps:"
TOKENS=512

# Get the arguments
while getopts "l:b:p:o:c:i:r:t:" arg; do
  case $arg in
    l) WORKLOAD=$OPTARG;;
    b) BASE=$OPTARG;;
    p) PAUSE=$OPTARG;;
    o) OPTIONS+=("$OPTARG");;
    c) COMMAND+=("$OPTARG");;
    i) INFERENCE=$OPTARG;;
    r) RUN=$OPTARG;;
    t) TOTAL=$OPTARG;;
    *) ;;
  esac
done


if [[ "$WORKLOAD" == "llama.cpp" ]]; then
  OPTIONS=(-v "${PWD}"/llama.cpp/models:/models)
  COMMAND=(-m /models/7B/ggml-model-q4_0.bin -p "${INFERENCE}" -n "${TOKENS}"--seed 12345678 --mlock)
elif [[ "$WORKLOAD" == "video-stream" ]]; then
  OPTIONS=(-p 8080:8080 --add-host=host.docker.internal:host-gateway)
fi

# Run and monitor the workload for the specified number of times
sleep ${PAUSE}
echo -e "# run ${RUN} (total: ${TOTAL}): ${BASE}" | tee -a results/"${WORKLOAD}"_"${BASE}".txt

# Run the monitoring tool on the docker run command
perf stat -o results/"${WORKLOAD}"_"${BASE}".txt --append -e power/energy-cores/,power/energy-ram/,power/energy-gpu/,power/energy-pkg/ \
docker run --name "${WORKLOAD}"-"${BASE}" "${OPTIONS[@]}" "${WORKLOAD}"-"${BASE}" "${COMMAND[@]}"

# Log the output of the run
date +"# run ${RUN} (total: ${TOTAL})%n# started on %c %n" >> logs/"${WORKLOAD}"_"${BASE}".txt
docker logs -f "${WORKLOAD}"-"${BASE}" &>> logs/"${WORKLOAD}"_"${BASE}".txt
echo -e "\n\n" | tee -a logs/"${WORKLOAD}"_"${BASE}".txt results/"${WORKLOAD}"_"${BASE}".txt
docker rm "${WORKLOAD}"-"${BASE}"