#!/bin/bash

# Default values
EXPID=-1
WORKLOAD="llama.cpp"
BASE=()
WARMUP=10
# WARMUP=10
INFERENCE="Building a website can be done in 10 simple steps:"
TOKENS=32
OPTIONS=()
COMMAND=()
CLIENT=false


# Get the arguments
while getopts "x:l:b:w:o:c:" arg; do
  case $arg in
    x) EXPID=$OPTARG;;
    l) WORKLOAD=$OPTARG;;
    b) BASE+=("$OPTARG");;
    w) WARMUP=$OPTARG;;
    o) OPTIONS+=("$OPTARG");;
    c) COMMAND+=("$OPTARG");;
    *) ;;
  esac
done


if [[ "$WORKLOAD" == "llama.cpp" ]]; then
  OPTIONS=(-v "${PWD}"/llama.cpp/models:/models)
  COMMAND=(-m /models/7B/ggml-model-q4_0.bin -p "${INFERENCE}" -n "${TOKENS}" --seed 12345678 -t 2)
elif [[ "$WORKLOAD" == "video-stream" ]]; then
  OPTIONS=(-p 8080:8080 --add-host=host.docker.internal:host-gateway)
elif [[ "$WORKLOAD" == "nginx-vod-module-docker" ]]; then
  OPTIONS=(-p 3030:80 -v "${PWD}"/nginx-vod-module-docker/examples/videos:/opt/static/videos -v "${PWD}"/workloads/nginx-vod-module-docker/nginx.conf:/usr/local/nginx/conf/nginx.conf)
  CLIENT=true
elif [[ "$WORKLOAD" == "flaskr" ]]; then
  OPTIONS=(-p 5000:5000)
  CLIENT=true
elif [[ "$WORKLOAD" == "cypress-realworld-app" ]]; then
  yarn --cwd "${PWD}"/cypress-realworld-app start:react &
  PID=$!
  OPTIONS=(-p 3001:3001)
  CLIENT=true
fi


# Setup the log files
mkdir -p logs
mkdir -p results
echo -e "### experiment ${EXPID} ###\n" >> logs/"${WORKLOAD}"_warmup.txt
date +"# started on %c %n" >> logs/"${WORKLOAD}"_warmup.txt

for i in "${BASE[@]}"; do
  echo -e "### experiment ${EXPID} ###\n# workload: ${WORKLOAD}\n# image: ${i}\n" | tee -a logs/"${WORKLOAD}"_"${i}".txt \
  results/"${WORKLOAD}"_"${i}".txt results/"${WORKLOAD}"_"${i}"_samples.txt
  # If alpine is selected, use the alpine Dockerfile;
  if [[ "$i" == "alpine" ]]; then 
    DOCKERFILE=DockerfileAlpine; 
  # If centos is selected, use the centos Dockerfile
  elif [[ "$i" == "centos" ]]; then
    DOCKERFILE=DockerfileCentos;
  else 
    DOCKERFILE=Dockerfile; 
  fi

  # Build the Docker image
  docker build -t "${WORKLOAD}"-"${i}" -f workloads/"${WORKLOAD}"/${DOCKERFILE} --build-arg BASE="${i}" "${WORKLOAD}"

  # Run the docker run command as warmup
  if ${CLIENT} ; then
    docker run --name "${WORKLOAD}"-"${i}" "${OPTIONS[@]}" "${WORKLOAD}"-"${i}" "${COMMAND[@]}" &
    bash workloads/"${WORKLOAD}"/client -b "${i}"
  else
    docker run --name "${WORKLOAD}"-"${i}" "${OPTIONS[@]}" "${WORKLOAD}"-"${i}" "${COMMAND[@]}"
  fi

  docker rm "${WORKLOAD}"-"${i}"
done

# Log the docker images information
echo -e "# docker images\n" >> logs/"${WORKLOAD}"_warmup.txt
docker image ls >> logs/"${WORKLOAD}"_warmup.txt

# Start the warm up procedure
echo -e "\n# warmup\n" >> logs/"${WORKLOAD}"_warmup.txt
sysbench cpu --time="${WARMUP}" --cpu-max-prime=100000 --threads=2 run | tee -a logs/"${WORKLOAD}"_warmup.txt
echo -e "\n\n" >> logs/"${WORKLOAD}"_warmup.txt


