#!/bin/bash
# Get the arguments
while getopts "b:au:" arg; do
  case $arg in
    b) BASE+=("$OPTARG");;
    a) BASE=("ubuntu" "debian" "alpine" "centos");;
    u) RUNID=$OPTARG;;
  esac
done

# Setup the log files
echo -e "### experiment ${RUNID} ###\n" | tee -a logs/llama.cpp_warmup.txt logs/llama.cpp_"${BASE}".txt results/llama.cpp_"${BASE}".txt
date +"# started on %c %n" >> logs/llama.cpp_warmup.txt

for i in "${BASE[@]}"; do
  # If alpine is selected, use the alpine Dockerfile;
  if [[ "$i" == "alpine" ]]; then 
    DOCKERFILE=DockerfileAlpine; 
  # If centos is selected, use the centos Dockerfile
  elif [[ "$i" == "centos" ]]; then
    DOCKERFILE=DockerfileCentos;
  else 
    DOCKERFILE=Dockerfile; 
  fi

  # Build the Docker image
  docker build -t llama.cpp-"${i}" -f llama.cpp/${DOCKERFILE} --build-arg BASE="${i}" llama.cpp
done

# Log the docker images information
echo -e "# docker images\n" >> logs/llama.cpp_warmup.txt
docker image ls >> logs/llama.cpp_warmup.txt

# Start the warm up procedure
echo -e "\n# warmup\n" >> logs/llama.cpp_warmup.txt
sysbench cpu --time=10 --cpu-max-prime=100000 --threads=2 run >> logs/llama.cpp_warmup.txt
echo -e "\n\n" >> logs/llama.cpp_warmup.txt
