#!/bin/bash

# Default values
BASE=()

# Get the arguments
while getopts "x:l:b:w:" arg; do
  case $arg in
    l) WORKLOAD=$OPTARG;;
    b) BASE+=("$OPTARG");;
    *) ;;
  esac
done

# Remove the docker images of this experiment
for i in "${BASE[@]}"; do
  docker rmi "${WORKLOAD}"-"${i}"
done