#!/bin/bash

# Default values
WORKLOAD="llama.cpp"
BASE=()

# Get the arguments
while getopts "l:b:x:" arg; do
  case $arg in
    l) WORKLOAD=$OPTARG;;
    b) BASE+=("$OPTARG");;
    *) ;;
  esac
done

echo "REMOVE WORKLOAD: ${WORKLOAD}"

docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' --filter=reference="${WORKLOAD}*")