#!/bin/bash

# Get the arguments
while getopts "b:w:x:" arg; do
  case $arg in
    b) BASE+=("$OPTARG");;
    w) WORKLOAD=$OPTARG;;
    *) ;;
  esac
done

# Default values
BASE=${BASE:-ubuntu}

# Remove the docker images of this experiment
for i in "${BASE[@]}"; do
  docker rmi "${WORKLOAD}"-"${i}"
done