#!/bin/bash

set_cpu() {
  systemctl set-property --runtime -- user.slice AllowedCPUs="$1"   
  systemctl set-property --runtime -- system.slice AllowedCPUs="$2"
}

RESET=true
ISOLATE="-1"
BACKGROUND="-1"

# Get the arguments
while getopts "sri:j:" arg; do
  case $arg in
    s) RESET=false;;
    r) RESET=true;;
    i) ISOLATE=$OPTARG;;
    j) BACKGROUND=$OPTARG;;
  esac
done

# Split the CPUs between the user and system slices based on total number of CPUs
CPUS=$(($(nproc --all) - 1))
SPLIT="$(($CPUS / 2))"

if [[ "$RESET" == true ]]; then
  set_cpu "0-$CPUS" "0-$CPUS"
else
#   set_cpu "0-$SPLIT" "$(($SPLIT + 1))-$CPUS"
  set_cpu "0-$SPLIT" "0-$CPUS"
fi

if [[ "$ISOLATE" != "-1" ]]; then
  set_cpu "$ISOLATE" "$ISOLATE"
fi
if [[ "$BACKGROUND" != "-1" ]]; then
  set_cpu "$BACKGROUND" "0-$CPUS"
fi

