ARG BASE=alpine@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70

FROM ${BASE} as build

COPY --from=binary . .

COPY --from=model /7B/ggml-model-q4_0.bin ./models/7B/ggml-model-q4_0.bin

ENTRYPOINT [ "/main" ]