ARG BASE=centos@sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc

FROM ${BASE} as build

COPY --from=binary . .

COPY --from=model /7B/ggml-model-q4_0.bin ./models/7B/ggml-model-q4_0.bin

ENTRYPOINT [ "/main" ]