#!/bin/bash

# Get the arguments
while getopts "b:" arg; do
  case $arg in
    b) BASE=$OPTARG;;
    *) ;;
  esac
done

until $(curl --output /dev/null --silent --head --fail localhost:3000); do
  echo "Waiting for server to start"
  sleep 5
done

# curl --head -X GET --retry 10 --retry-connrefused --retry-delay 5 localhost:3000/personal

echo "Server started, running tests"

source ~/.nvm/nvm.sh
nvm use 16

yarn --cwd ${PWD}/cypress-realworld-app/ db:seed:dev && \
yarn --cwd ${PWD}/cypress-realworld-app/ predev:cognito:ci

yarn --cwd ${PWD}/cypress-realworld-app/ cypress run --config video=false

# docker stop cypress-realworld-app-"${BASE/:/}"

docker compose -f ${PWD}/workloads/cypress-realworld-app/docker-compose.yml down