FROM node:16

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install && yarn cache clean;

RUN apt-get update && \
    apt-get install --no-install-recommends -y curl
    
COPY . .

ENV NODE_ENV=development
ENV BROWSER=none

RUN yarn db:seed:dev && \
    yarn predev:cognito:ci

EXPOSE 3000

CMD [ "yarn", "start:react" ]