FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Europe/Amsterdam

RUN apt-get update && apt-get install -y postgresql-client postgresql-contrib

COPY docker-entry-client.sh .

RUN chmod +x ./docker-entry-client.sh

ENTRYPOINT ./docker-entry-client.sh