ARG BASE=alpine@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70

FROM ${BASE} as build

RUN apk update && apk add --no-cache build-base

WORKDIR /app

COPY main.c main.c

RUN gcc -o main main.c

ENTRYPOINT ["./main"]
