#!/bin/bash

# Get the arguments
while getopts "b:" arg; do
  case $arg in
    b) BASE=$OPTARG;;
    *) ;;
  esac
done

# until $(curl --output /dev/null --silent --head --fail http://localhost:8065/signup_user_complete); do
# while ! echo exit | nc localhost 8065; do
while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8065)" != "200" ]]; do
  echo "Waiting for server to start"
  sleep 5
done

echo "Server started, running tests"


npm run cypress:run --prefix ${PWD}/mattermost/e2e-tests/cypress -- \
--spec "${PWD}/mattermost/e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js,\
${PWD}/mattermost/e2e-tests/cypress/tests/integration/channels/account_settings/profile/account_settings_position_spec.ts,\
${PWD}/mattermost/e2e-tests/cypress/tests/integration/channels/autocomplete/database/users_in_channel_switcher_spec.js" \
--config video=false

# docker stop mattermost-"${BASE/:/}" 
docker compose -f ${PWD}/workloads/mattermost/docker-compose.yml down