# Copyright (c) 2016-present Mattermost, Inc. All Rights Reserved.
# See License.txt for license information.
# FROM debian:latest
ARG BASE=centos:latest

FROM ${BASE}

RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum update -y \
    && yum install -y ca-certificates curl && rm -rf /var/cache/yum

ENV MYSQL_ROOT_PASSWORD=mostest
ENV MYSQL_USER=mmuser
ENV MYSQL_PASSWORD=mostest
ENV MYSQL_DATABASE=mattermost_test

WORKDIR /mm

# Copy over files
ADD https://releases.mattermost.com/7.10.2/mattermost-team-7.10.2-linux-amd64.tar.gz .
RUN tar -zxvf mattermost-team-*-linux-amd64.tar.gz && rm mattermost-team-*-linux-amd64.tar.gz
COPY config_docker.json ./mattermost/config/config_docker.json
COPY docker-centos-entry.sh .

RUN chmod +x ./docker-centos-entry.sh
ENTRYPOINT ./docker-centos-entry.sh

# Mattermost environment variables
ENV PATH="/mm/mattermost/bin:${PATH}"

# Create default storage directory
RUN mkdir ./mattermost-data
# VOLUME /mm/mattermost-data

# Ports
EXPOSE 8065
