ARG BASE=alpine@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629874104f8a7f70

FROM ${BASE} as build

RUN apk update && apk add --no-cache redis

EXPOSE 6379

CMD ["redis-server", "--protected-mode no"]