ARG BASE=centos:latest

FROM ${BASE} as build


RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum update -y \
    && yum install -y redis && rm -rf /var/cache/yum

EXPOSE 6379

CMD ["redis-server", "--protected-mode no"]