ARG BASE=centos:latest

FROM ${BASE} AS base_image

FROM base_image AS build

RUN cd /etc/yum.repos.d/  \
&& sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
&& sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
&& yum update -y \
&& dnf -y install epel-release epel-next-release 'dnf-command(config-manager)' \
&& dnf config-manager --set-enabled powertools \
&& dnf install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm \
&& dnf install -y https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm \
&& dnf -y install ffmpeg \
&& yum install -y curl supervisor gcc gcc-c++ make pcre-devel openssl-devel zlib-devel && rm -rf /var/cache/yum

RUN mkdir nginx nginx-vod-module

ARG NGINX_VERSION=1.23.4
ARG VOD_MODULE_VERSION=6c305a78b7ab6e4312279bea5c45741bb54a713b

WORKDIR /home

RUN curl -sL https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz | tar -C /nginx --strip 1 -xz
RUN curl -sL https://github.com/kaltura/nginx-vod-module/archive/${VOD_MODULE_VERSION}.tar.gz | tar -C /nginx-vod-module --strip 1 -xz

WORKDIR /nginx
RUN ./configure --prefix=/usr/local/nginx \
--add-module=../nginx-vod-module \
--with-http_ssl_module \
--with-file-aio \
--with-threads \
--with-cc-opt="-O3"
RUN make
RUN make install
RUN rm -rf /usr/local/nginx/html /usr/local/nginx/conf/*.default

FROM base_image
RUN cd /etc/yum.repos.d/ && \
sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
&& yum update -y && \
yum install -y ca-certificates openssl pcre zlib && rm -rf /var/cache/yum
COPY --from=build /usr/local/nginx /usr/local/nginx
ENTRYPOINT ["/usr/local/nginx/sbin/nginx"]
CMD ["-g", "daemon off;"]
